Two Factor Authentication
spark/spark-setup-android pull request #65
Opened 2018-08-06 13:24 UTC by CityVibes

Feel free to review code, note: **DO NOT MERGE** - need to update cloudsdk to 0.5.1 (once released) for 2fa flow to work.

2018-08-06 16:51 UTC, RaimundasSakalauskas commented on devicesetup/src/main/res/values/strings.xml
> +    <string name="title_activity_two_factor">Two Factor Authentication</string>
@channel — something we decided in our stand up today around communication:

- In _internal_ and _technical_ communications, we will refer to this feature as *multi-factor authentication (MFA)*
- In _external_ and _customer-facing_ communications, we will refer to this feature as *two-step authentication*

2018-08-06 16:52 UTC, RaimundasSakalauskas approved these changes
Except that one string I commented, looks good to me.

2018-08-07 00:08 UTC, jensck requested changes
The `isFinishing()` thing in `TwoFactorActivity` needs to be fixed, everything else is optional/future reference!

2018-08-07 00:08 UTC, jensck commented on devicesetup/src/main/java/io/particle/android/sdk/accountsetup/TwoFactorActivity.java
> +        ParticleDeviceSetupLibrary.getInstance().getApplicationComponent().activityComponentBuilder()
bro, do you even line break?  ;)

Again, not blocking PR for this, but in the future, let's use builder-style wrapping for this kind of long call chain.

2018-08-07 00:08 UTC, jensck commented on devicesetup/src/main/java/io/particle/android/sdk/accountsetup/TwoFactorActivity.java
> +                log.d("onFailed(): " + error.getMessage());
This should have the same `if (isFinishing())` call here as in `onSuccess()`.

2018-08-07 19:49 UTC, jensck commented on devicesetup/src/main/java/io/particle/android/sdk/accountsetup/LoginActivity.java
> +        ParticleDeviceSetupLibrary
:+1: thanks!

2018-08-07 19:50 UTC, jensck commented on devicesetup/src/main/java/io/particle/android/sdk/accountsetup/TwoFactorActivity.java
> +    public static Intent buildIntent(Context context, String email, String password, String mfa) {
+1 for adding this.

2018-08-07 19:51 UTC, jensck approved these changes

2018-08-07 19:51 UTC, jensck commented
LGTM

2018-08-08 13:21 UTC, merged